In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('HR_Dataset.csv')
X= dataset.loc[:, dataset.columns!='column7']
y = dataset.iloc[:, -4].values

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [8, 9])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [6]:
print(X_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [7]:
print(y_train)

[0 1 0 ... 0 0 0]


In [8]:
print(X_test)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
print(y_test)

[1 0 0 ... 0 0 0]


In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train)

[[-0.29800108 -0.23684279 -0.23315715 ... -0.41103163 -0.55878327
  -0.14921224]
 [-0.29800108 -0.23684279 -0.23315715 ... -0.41103163  1.7896026
  -0.14921224]
 [-0.29800108 -0.23684279 -0.23315715 ...  2.43290277 -0.55878327
  -0.14921224]
 ...
 [ 3.35569249 -0.23684279 -0.23315715 ... -0.41103163 -0.55878327
  -0.14921224]
 [-0.29800108 -0.23684279 -0.23315715 ... -0.41103163 -0.55878327
  -0.14921224]
 [ 3.35569249 -0.23684279 -0.23315715 ... -0.41103163 -0.55878327
  -0.14921224]]


In [12]:
print(X_test)

[[-0.29800108 -0.23684279 -0.23315715 ... -0.41103163  1.7896026
  -0.14921224]
 [-0.29800108 -0.23684279 -0.23315715 ... -0.41103163 -0.55878327
  -0.14921224]
 [-0.29800108 -0.23684279 -0.23315715 ... -0.41103163 -0.55878327
  -0.14921224]
 ...
 [-0.29800108 -0.23684279 -0.23315715 ... -0.41103163 -0.55878327
  -0.14921224]
 [-0.29800108 -0.23684279 -0.23315715 ... -0.41103163 -0.55878327
  -0.14921224]
 [-0.29800108 -0.23684279 -0.23315715 ... -0.41103163 -0.55878327
  -0.14921224]]


In [13]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [15]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 99.99 %
Standard Deviation: 0.02 %
