# Multiple Linear Regression

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Wellbeing_and_lifestyle_data_Kaggle.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[3 '2' 2 ... 5 '36 to 50' 'Female']
 [2 '3' 4 ... 6 '36 to 50' 'Female']
 [2 '3' 3 ... 3 '36 to 50' 'Female']
 ...
 [4 '3' 0 ... 10 '21 to 35' 'Male']
 [1 '1' 10 ... 8 '21 to 35' 'Female']
 [5 '4' 0 ... 4 '21 to 35' 'Female']]


## Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1, 20, 21])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 0.0 0.0 ... 4 0 5]
 [0.0 0.0 0.0 ... 3 2 6]
 [0.0 0.0 0.0 ... 4 8 3]
 ...
 [0.0 0.0 0.0 ... 10 1 10]
 [0.0 0.0 1.0 ... 1 6 8]
 [0.0 0.0 0.0 ... 1 8 4]]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
print(X)

[[0.0 0.0 0.0 ... 4 0 5]
 [0.0 0.0 0.0 ... 3 2 6]
 [0.0 0.0 0.0 ... 4 8 3]
 ...
 [0.0 0.0 0.0 ... 10 1 10]
 [0.0 0.0 1.0 ... 1 6 8]
 [0.0 0.0 0.0 ... 1 8 4]]


## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[632.6 632.6]
 [652.  652. ]
 [647.5 647.5]
 ...
 [722.7 722.7]
 [631.2 631.2]
 [647.1 647.1]]
